<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/video16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [19]:
d=pd.read_csv("/content/diabetes.csv")

In [20]:
type(d)

pandas.core.frame.DataFrame

In [21]:
d.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [23]:
d.shape

(768, 9)

In [26]:
d.to_excel('diabetes.csv')

ValueError: No engine for filetype: 'csv'

In [39]:
import numpy as np
r=pd.DataFrame(np.random.rand(30,4))
print(r)

           0         1         2         3
0   0.110868  0.656806  0.416730  0.237193
1   0.300435  0.650800  0.311965  0.492153
2   0.001902  0.539247  0.328869  0.187776
3   0.482004  0.249763  0.587465  0.131712
4   0.066452  0.196302  0.306588  0.356703
5   0.772630  0.864412  0.527604  0.725892
6   0.503076  0.488161  0.496743  0.982926
7   0.278139  0.757524  0.610417  0.118798
8   0.530143  0.801174  0.021339  0.158802
9   0.025756  0.813665  0.318608  0.952667
10  0.524160  0.793383  0.320025  0.034375
11  0.294186  0.970272  0.864877  0.394385
12  0.300199  0.122463  0.674709  0.728114
13  0.793579  0.430124  0.351754  0.371523
14  0.664099  0.805305  0.654934  0.758383
15  0.986428  0.620848  0.746311  0.812414
16  0.946659  0.477960  0.887806  0.530976
17  0.565078  0.672963  0.501099  0.910765
18  0.141982  0.639849  0.895722  0.952429
19  0.380166  0.104645  0.630724  0.430001
20  0.306233  0.668766  0.631488  0.317560
21  0.613803  0.260040  0.539399  0.609459
22  0.082679  0.516151  0.868041  0.717793
23  0.440737  0.463952  0.994803  0.768491
24  0.022461  0.189833  0.131530  0.623034
25  0.222586  0.842020  0.489200  0.849069
26  0.106866  0.494333  0.213976  0.669997
27  0.701015  0.805516  0.982645  0.134826
28  0.062771  0.132514  0.677144  0.763614
29  0.689192  0.651452  0.082503  0.659619

In [40]:
r.head()

          0         1         2         3
0  0.110868  0.656806  0.416730  0.237193
1  0.300435  0.650800  0.311965  0.492153
2  0.001902  0.539247  0.328869  0.187776
3  0.482004  0.249763  0.587465  0.131712
4  0.066452  0.196302  0.306588  0.356703

In [41]:
r.shape

(30, 4)

In [42]:
r.shape

(30, 4)

In [43]:
r.tail()

           0         1         2         3
25  0.222586  0.842020  0.489200  0.849069
26  0.106866  0.494333  0.213976  0.669997
27  0.701015  0.805516  0.982645  0.134826
28  0.062771  0.132514  0.677144  0.763614
29  0.689192  0.651452  0.082503  0.659619

In [44]:
r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       30 non-null     float64
 1   1       30 non-null     float64
 2   2       30 non-null     float64
 3   3       30 non-null     float64
dtypes: float64(4)
memory usage: 1.1 KB

In [45]:
r.isnull()

        0      1      2      3
0   False  False  False  False
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False  False  False
5   False  False  False  False
6   False  False  False  False
7   False  False  False  False
8   False  False  False  False
9   False  False  False  False
10  False  False  False  False
11  False  False  False  False
12  False  False  False  False
13  False  False  False  False
14  False  False  False  False
15  False  False  False  False
16  False  False  False  False
17  False  False  False  False
18  False  False  False  False
19  False  False  False  False
20  False  False  False  False
21  False  False  False  False
22  False  False  False  False
23  False  False  False  False
24  False  False  False  False
25  False  False  False  False
26  False  False  False  False
27  False  False  False  False
28  False  False  False  False
29  False  False  False  False

In [56]:
r.value_counts(2)

2
0.021339    1
0.082503    1
0.131530    1
0.213976    1
0.306588    1
0.311965    1
0.318608    1
0.320025    1
0.328869    1
0.351754    1
0.416730    1
0.489200    1
0.496743    1
0.501099    1
0.527604    1
0.539399    1
0.587465    1
0.610417    1
0.630724    1
0.631488    1
0.654934    1
0.674709    1
0.677144    1
0.746311    1
0.864877    1
0.868041    1
0.887806    1
0.895722    1
0.982645    1
0.994803    1
Name: count, dtype: int64

In [55]:
r.groupby(2).mean()

                 0         1         3
2
0.021339  0.530143  0.801174  0.158802
0.082503  0.689192  0.651452  0.659619
0.131530  0.022461  0.189833  0.623034
0.213976  0.106866  0.494333  0.669997
0.306588  0.066452  0.196302  0.356703
0.311965  0.300435  0.650800  0.492153
0.318608  0.025756  0.813665  0.952667
0.320025  0.524160  0.793383  0.034375
0.328869  0.001902  0.539247  0.187776
0.351754  0.793579  0.430124  0.371523
0.416730  0.110868  0.656806  0.237193
0.489200  0.222586  0.842020  0.849069
0.496743  0.503076  0.488161  0.982926
0.501099  0.565078  0.672963  0.910765
0.527604  0.772630  0.864412  0.725892
0.539399  0.613803  0.260040  0.609459
0.587465  0.482004  0.249763  0.131712
0.610417  0.278139  0.757524  0.118798
0.630724  0.380166  0.104645  0.430001
0.631488  0.306233  0.668766  0.317560
0.654934  0.664099  0.805305  0.758383
0.674709  0.300199  0.122463  0.728114
0.677144  0.062771  0.132514  0.763614
0.746311  0.986428  0.620848  0.812414
0.864877  0.294186  0.970272  0.394385
0.868041  0.082679  0.516151  0.717793
0.887806  0.946659  0.477960  0.530976
0.895722  0.141982  0.639849  0.952429
0.982645  0.701015  0.805516  0.134826
0.994803  0.440737  0.463952  0.768491

In [57]:
r.count()

0    30
1    30
2    30
3    30
dtype: int64

In [58]:
r.mean()

0    0.397209
1    0.556008
2    0.535501
3    0.546048
dtype: float64

In [59]:
r.std()

0    0.287318
1    0.250437
2    0.264969
3    0.288228
dtype: float64

In [60]:
r.min()

0    0.001902
1    0.104645
2    0.021339
3    0.034375
dtype: float64

In [61]:
r.max()

0    0.986428
1    0.970272
2    0.994803
3    0.982926
dtype: float64

In [62]:
r.describe()

               0          1          2          3
count  30.000000  30.000000  30.000000  30.000000
mean    0.397209   0.556008   0.535501   0.546048
std     0.287318   0.250437   0.264969   0.288228
min     0.001902   0.104645   0.021339   0.034375
25%     0.118646   0.438581   0.322236   0.327346
50%     0.343199   0.630348   0.533502   0.616247
75%     0.601622   0.784418   0.676535   0.762306
max     0.986428   0.970272   0.994803   0.982926

In [67]:
r.drop(2)

           0         1         2         3
0   0.110868  0.656806  0.416730  0.237193
1   0.300435  0.650800  0.311965  0.492153
3   0.482004  0.249763  0.587465  0.131712
4   0.066452  0.196302  0.306588  0.356703
5   0.772630  0.864412  0.527604  0.725892
6   0.503076  0.488161  0.496743  0.982926
7   0.278139  0.757524  0.610417  0.118798
8   0.530143  0.801174  0.021339  0.158802
9   0.025756  0.813665  0.318608  0.952667
10  0.524160  0.793383  0.320025  0.034375
11  0.294186  0.970272  0.864877  0.394385
12  0.300199  0.122463  0.674709  0.728114
13  0.793579  0.430124  0.351754  0.371523
14  0.664099  0.805305  0.654934  0.758383
15  0.986428  0.620848  0.746311  0.812414
16  0.946659  0.477960  0.887806  0.530976
17  0.565078  0.672963  0.501099  0.910765
18  0.141982  0.639849  0.895722  0.952429
19  0.380166  0.104645  0.630724  0.430001
20  0.306233  0.668766  0.631488  0.317560
21  0.613803  0.260040  0.539399  0.609459
22  0.082679  0.516151  0.868041  0.717793
23  0.440737  0.463952  0.994803  0.768491
24  0.022461  0.189833  0.131530  0.623034
25  0.222586  0.842020  0.489200  0.849069
26  0.106866  0.494333  0.213976  0.669997
27  0.701015  0.805516  0.982645  0.134826
28  0.062771  0.132514  0.677144  0.763614
29  0.689192  0.651452  0.082503  0.659619

In [65]:
r.shape

(30, 4)

In [75]:
r.drop(columns=2,axis=1)

           0         1         3
0   0.110868  0.656806  0.237193
1   0.300435  0.650800  0.492153
2   0.001902  0.539247  0.187776
3   0.482004  0.249763  0.131712
4   0.066452  0.196302  0.356703
5   0.772630  0.864412  0.725892
6   0.503076  0.488161  0.982926
7   0.278139  0.757524  0.118798
8   0.530143  0.801174  0.158802
9   0.025756  0.813665  0.952667
10  0.524160  0.793383  0.034375
11  0.294186  0.970272  0.394385
12  0.300199  0.122463  0.728114
13  0.793579  0.430124  0.371523
14  0.664099  0.805305  0.758383
15  0.986428  0.620848  0.812414
16  0.946659  0.477960  0.530976
17  0.565078  0.672963  0.910765
18  0.141982  0.639849  0.952429
19  0.380166  0.104645  0.430001
20  0.306233  0.668766  0.317560
21  0.613803  0.260040  0.609459
22  0.082679  0.516151  0.717793
23  0.440737  0.463952  0.768491
24  0.022461  0.189833  0.623034
25  0.222586  0.842020  0.849069
26  0.106866  0.494333  0.669997
27  0.701015  0.805516  0.134826
28  0.062771  0.132514  0.763614
29  0.689192  0.651452  0.659619

In [77]:
r.iloc[3]

0    0.482004
1    0.249763
2    0.587465
3    0.131712
Name: 3, dtype: float64

In [84]:
r.drop(index=1,axis=1)

           0         1         2         3
0   0.110868  0.656806  0.416730  0.237193
2   0.001902  0.539247  0.328869  0.187776
3   0.482004  0.249763  0.587465  0.131712
4   0.066452  0.196302  0.306588  0.356703
5   0.772630  0.864412  0.527604  0.725892
6   0.503076  0.488161  0.496743  0.982926
7   0.278139  0.757524  0.610417  0.118798
8   0.530143  0.801174  0.021339  0.158802
9   0.025756  0.813665  0.318608  0.952667
10  0.524160  0.793383  0.320025  0.034375
11  0.294186  0.970272  0.864877  0.394385
12  0.300199  0.122463  0.674709  0.728114
13  0.793579  0.430124  0.351754  0.371523
14  0.664099  0.805305  0.654934  0.758383
15  0.986428  0.620848  0.746311  0.812414
16  0.946659  0.477960  0.887806  0.530976
17  0.565078  0.672963  0.501099  0.910765
18  0.141982  0.639849  0.895722  0.952429
19  0.380166  0.104645  0.630724  0.430001
20  0.306233  0.668766  0.631488  0.317560
21  0.613803  0.260040  0.539399  0.609459
22  0.082679  0.516151  0.868041  0.717793
23  0.440737  0.463952  0.994803  0.768491
24  0.022461  0.189833  0.131530  0.623034
25  0.222586  0.842020  0.489200  0.849069
26  0.106866  0.494333  0.213976  0.669997
27  0.701015  0.805516  0.982645  0.134826
28  0.062771  0.132514  0.677144  0.763614
29  0.689192  0.651452  0.082503  0.659619

In [85]:
r.iloc[:0]

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [86]:
r.iloc[:1]

          0         1        2         3
0  0.110868  0.656806  0.41673  0.237193

In [88]:

r.iloc[:3]

          0         1         2         3
0  0.110868  0.656806  0.416730  0.237193
1  0.300435  0.650800  0.311965  0.492153
2  0.001902  0.539247  0.328869  0.187776

In [89]:
r.iloc[:,-1]

0     0.237193
1     0.492153
2     0.187776
3     0.131712
4     0.356703
5     0.725892
6     0.982926
7     0.118798
8     0.158802
9     0.952667
10    0.034375
11    0.394385
12    0.728114
13    0.371523
14    0.758383
15    0.812414
16    0.530976
17    0.910765
18    0.952429
19    0.430001
20    0.317560
21    0.609459
22    0.717793
23    0.768491
24    0.623034
25    0.849069
26    0.669997
27    0.134826
28    0.763614
29    0.659619
Name: 3, dtype: float64

In [90]:
r.corr()

          0         1         2         3
0  1.000000  0.198946  0.196088 -0.016054
1  0.198946  1.000000  0.017821 -0.062757
2  0.196088  0.017821  1.000000  0.167032
3 -0.016054 -0.062757  0.167032  1.000000